apiVersion: v1
kind: Secret
metadata:
  name: polar-credentials
  namespace: orzbob-system
type: Opaque
stringData:
  api-key: "${POLAR_API_KEY}"
  webhook-secret: "${POLAR_WEBHOOK_SECRET}"
  project-id: "${POLAR_PROJECT_ID}"
---
# Example of how to create this secret:
# kubectl create secret generic polar-credentials \
#   --namespace=orzbob-system \
#   --from-literal=api-key='polar_sk_...' \
#   --from-literal=webhook-secret='whsec_...' \
#   --from-literal=project-id='proj_...'