# Fluent Bit configuration for Orzbob Cloud
# This configures log collection from all pods in the cluster

image:
  repository: fluent/fluent-bit
  tag: 2.1.10
  pullPolicy: IfNotPresent

# Fluent Bit configuration
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/orzbob-*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name modify
        Match kube.*
        Add cluster orzbob-cloud
        Add environment production

  outputs: |
    [OUTPUT]
        Name stdout
        Match *
        Format json_lines

    # In production, this would send to a log aggregation service
    # [OUTPUT]
    #     Name es
    #     Match kube.*
    #     Host elasticsearch.logging.svc.cluster.local
    #     Port 9200
    #     Logstash_Format On
    #     Logstash_Prefix orzbob
    #     Retry_Limit False

  parsers: |
    [PARSER]
        Name json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

# DaemonSet configuration
daemonset:
  enabled: true
  
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

rbac:
  create: true

serviceAccount:
  create: true
  name: fluent-bit

# Volume mounts for log collection
volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: config
    mountPath: /fluent-bit/etc/

volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: config
    configMap:
      name: fluent-bit-config