apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cp
  namespace: orzbob-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-cp
  template:
    metadata:
      labels:
        app: cloud-cp
    spec:
      serviceAccountName: cloud-cp
      containers:
      - name: cloud-cp
        image: orzbob/cloud-cp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        # Kubernetes configuration
        - name: IN_CLUSTER
          value: "true"
        # Polar billing credentials from secret
        - name: POLAR_API_KEY
          valueFrom:
            secretKeyRef:
              name: polar-credentials
              key: api-key
        - name: POLAR_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: polar-credentials
              key: webhook-secret
        - name: POLAR_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: polar-credentials
              key: project-id
        # Optional: billing mode
        - name: BILLING_ENABLED
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-cp
  namespace: orzbob-system
spec:
  selector:
    app: cloud-cp
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-cp
  namespace: orzbob-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-cp
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-cp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-cp
subjects:
- kind: ServiceAccount
  name: cloud-cp
  namespace: orzbob-system