// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/cloud/api/instance.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceStatus int32

const (
	InstanceStatus_INSTANCE_STATUS_UNSPECIFIED InstanceStatus = 0
	InstanceStatus_INSTANCE_STATUS_PENDING     InstanceStatus = 1
	InstanceStatus_INSTANCE_STATUS_RUNNING     InstanceStatus = 2
	InstanceStatus_INSTANCE_STATUS_TERMINATING InstanceStatus = 3
	InstanceStatus_INSTANCE_STATUS_TERMINATED  InstanceStatus = 4
	InstanceStatus_INSTANCE_STATUS_FAILED      InstanceStatus = 5
)

// Enum value maps for InstanceStatus.
var (
	InstanceStatus_name = map[int32]string{
		0: "INSTANCE_STATUS_UNSPECIFIED",
		1: "INSTANCE_STATUS_PENDING",
		2: "INSTANCE_STATUS_RUNNING",
		3: "INSTANCE_STATUS_TERMINATING",
		4: "INSTANCE_STATUS_TERMINATED",
		5: "INSTANCE_STATUS_FAILED",
	}
	InstanceStatus_value = map[string]int32{
		"INSTANCE_STATUS_UNSPECIFIED": 0,
		"INSTANCE_STATUS_PENDING":     1,
		"INSTANCE_STATUS_RUNNING":     2,
		"INSTANCE_STATUS_TERMINATING": 3,
		"INSTANCE_STATUS_TERMINATED":  4,
		"INSTANCE_STATUS_FAILED":      5,
	}
)

func (x InstanceStatus) Enum() *InstanceStatus {
	p := new(InstanceStatus)
	*p = x
	return p
}

func (x InstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_cloud_api_instance_proto_enumTypes[0].Descriptor()
}

func (InstanceStatus) Type() protoreflect.EnumType {
	return &file_internal_cloud_api_instance_proto_enumTypes[0]
}

func (x InstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceStatus.Descriptor instead.
func (InstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{0}
}

// Instance represents a cloud runner instance
type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"` // small, medium, gpu
	Status        InstanceStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=orzbob.cloud.api.v1.InstanceStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AttachUrl     string                 `protobuf:"bytes,8,opt,name=attach_url,json=attachUrl,proto3" json:"attach_url,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Instance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Instance) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Instance) GetStatus() InstanceStatus {
	if x != nil {
		return x.Status
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *Instance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Instance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Instance) GetAttachUrl() string {
	if x != nil {
		return x.AttachUrl
	}
	return ""
}

func (x *Instance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateInstanceRequest for creating a new instance
type CreateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       string                 `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"` // e.g., "claude", "aider"
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`       // small (default), medium, gpu
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RepoUrl       string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstanceRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *CreateInstanceRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *CreateInstanceRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateInstanceRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *CreateInstanceRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// CreateInstanceResponse returns the created instance
type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// GetInstanceRequest for retrieving an instance
type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{3}
}

func (x *GetInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetInstanceResponse returns the requested instance
type GetInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{4}
}

func (x *GetInstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// ListInstancesRequest for listing instances
type ListInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{5}
}

func (x *ListInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInstancesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListInstancesResponse returns a list of instances
type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{6}
}

func (x *ListInstancesResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DeleteInstanceRequest for terminating an instance
type DeleteInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteInstanceResponse confirms deletion
type DeleteInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceResponse) Reset() {
	*x = DeleteInstanceResponse{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceResponse) ProtoMessage() {}

func (x *DeleteInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInstanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// AttachRequest for getting WebSocket URL
type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{9}
}

func (x *AttachRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// AttachResponse returns signed WebSocket URL
type AttachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WsUrl         string                 `protobuf:"bytes,1,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_internal_cloud_api_instance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cloud_api_instance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_internal_cloud_api_instance_proto_rawDescGZIP(), []int{10}
}

func (x *AttachResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *AttachResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_internal_cloud_api_instance_proto protoreflect.FileDescriptor

const file_internal_cloud_api_instance_proto_rawDesc = "" +
	"\n" +
	"!internal/cloud/api/instance.proto\x12\x13orzbob.cloud.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x03\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.orzbob.cloud.api.v1.InstanceStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"attach_url\x18\b \x01(\tR\tattachUrl\x12G\n" +
	"\bmetadata\x18\t \x03(\v2+.orzbob.cloud.api.v1.Instance.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x15CreateInstanceRequest\x12\x18\n" +
	"\aprogram\x18\x01 \x01(\tR\aprogram\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12E\n" +
	"\x03env\x18\x03 \x03(\v23.orzbob.cloud.api.v1.CreateInstanceRequest.EnvEntryR\x03env\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x16CreateInstanceResponse\x129\n" +
	"\binstance\x18\x01 \x01(\v2\x1d.orzbob.cloud.api.v1.InstanceR\binstance\"$\n" +
	"\x12GetInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x13GetInstanceResponse\x129\n" +
	"\binstance\x18\x01 \x01(\v2\x1d.orzbob.cloud.api.v1.InstanceR\binstance\"R\n" +
	"\x14ListInstancesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"|\n" +
	"\x15ListInstancesResponse\x12;\n" +
	"\tinstances\x18\x01 \x03(\v2\x1d.orzbob.cloud.api.v1.InstanceR\tinstances\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"'\n" +
	"\x15DeleteInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\rAttachRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"b\n" +
	"\x0eAttachResponse\x12\x15\n" +
	"\x06ws_url\x18\x01 \x01(\tR\x05wsUrl\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt*\xc8\x01\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17INSTANCE_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17INSTANCE_STATUS_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_TERMINATING\x10\x03\x12\x1e\n" +
	"\x1aINSTANCE_STATUS_TERMINATED\x10\x04\x12\x1a\n" +
	"\x16INSTANCE_STATUS_FAILED\x10\x052\x84\x04\n" +
	"\x0fInstanceService\x12i\n" +
	"\x0eCreateInstance\x12*.orzbob.cloud.api.v1.CreateInstanceRequest\x1a+.orzbob.cloud.api.v1.CreateInstanceResponse\x12`\n" +
	"\vGetInstance\x12'.orzbob.cloud.api.v1.GetInstanceRequest\x1a(.orzbob.cloud.api.v1.GetInstanceResponse\x12f\n" +
	"\rListInstances\x12).orzbob.cloud.api.v1.ListInstancesRequest\x1a*.orzbob.cloud.api.v1.ListInstancesResponse\x12i\n" +
	"\x0eDeleteInstance\x12*.orzbob.cloud.api.v1.DeleteInstanceRequest\x1a+.orzbob.cloud.api.v1.DeleteInstanceResponse\x12Q\n" +
	"\x06Attach\x12\".orzbob.cloud.api.v1.AttachRequest\x1a#.orzbob.cloud.api.v1.AttachResponseB\xb8\x01\n" +
	"\x17com.orzbob.cloud.api.v1B\rInstanceProtoP\x01Z\x1forzbob/internal/cloud/api;apiv1\xa2\x02\x03OCA\xaa\x02\x13Orzbob.Cloud.Api.V1\xca\x02\x13Orzbob\\Cloud\\Api\\V1\xe2\x02\x1fOrzbob\\Cloud\\Api\\V1\\GPBMetadata\xea\x02\x16Orzbob::Cloud::Api::V1b\x06proto3"

var (
	file_internal_cloud_api_instance_proto_rawDescOnce sync.Once
	file_internal_cloud_api_instance_proto_rawDescData []byte
)

func file_internal_cloud_api_instance_proto_rawDescGZIP() []byte {
	file_internal_cloud_api_instance_proto_rawDescOnce.Do(func() {
		file_internal_cloud_api_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cloud_api_instance_proto_rawDesc), len(file_internal_cloud_api_instance_proto_rawDesc)))
	})
	return file_internal_cloud_api_instance_proto_rawDescData
}

var file_internal_cloud_api_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_cloud_api_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_cloud_api_instance_proto_goTypes = []any{
	(InstanceStatus)(0),            // 0: orzbob.cloud.api.v1.InstanceStatus
	(*Instance)(nil),               // 1: orzbob.cloud.api.v1.Instance
	(*CreateInstanceRequest)(nil),  // 2: orzbob.cloud.api.v1.CreateInstanceRequest
	(*CreateInstanceResponse)(nil), // 3: orzbob.cloud.api.v1.CreateInstanceResponse
	(*GetInstanceRequest)(nil),     // 4: orzbob.cloud.api.v1.GetInstanceRequest
	(*GetInstanceResponse)(nil),    // 5: orzbob.cloud.api.v1.GetInstanceResponse
	(*ListInstancesRequest)(nil),   // 6: orzbob.cloud.api.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),  // 7: orzbob.cloud.api.v1.ListInstancesResponse
	(*DeleteInstanceRequest)(nil),  // 8: orzbob.cloud.api.v1.DeleteInstanceRequest
	(*DeleteInstanceResponse)(nil), // 9: orzbob.cloud.api.v1.DeleteInstanceResponse
	(*AttachRequest)(nil),          // 10: orzbob.cloud.api.v1.AttachRequest
	(*AttachResponse)(nil),         // 11: orzbob.cloud.api.v1.AttachResponse
	nil,                            // 12: orzbob.cloud.api.v1.Instance.MetadataEntry
	nil,                            // 13: orzbob.cloud.api.v1.CreateInstanceRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_internal_cloud_api_instance_proto_depIdxs = []int32{
	0,  // 0: orzbob.cloud.api.v1.Instance.status:type_name -> orzbob.cloud.api.v1.InstanceStatus
	14, // 1: orzbob.cloud.api.v1.Instance.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: orzbob.cloud.api.v1.Instance.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: orzbob.cloud.api.v1.Instance.metadata:type_name -> orzbob.cloud.api.v1.Instance.MetadataEntry
	13, // 4: orzbob.cloud.api.v1.CreateInstanceRequest.env:type_name -> orzbob.cloud.api.v1.CreateInstanceRequest.EnvEntry
	1,  // 5: orzbob.cloud.api.v1.CreateInstanceResponse.instance:type_name -> orzbob.cloud.api.v1.Instance
	1,  // 6: orzbob.cloud.api.v1.GetInstanceResponse.instance:type_name -> orzbob.cloud.api.v1.Instance
	1,  // 7: orzbob.cloud.api.v1.ListInstancesResponse.instances:type_name -> orzbob.cloud.api.v1.Instance
	14, // 8: orzbob.cloud.api.v1.AttachResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 9: orzbob.cloud.api.v1.InstanceService.CreateInstance:input_type -> orzbob.cloud.api.v1.CreateInstanceRequest
	4,  // 10: orzbob.cloud.api.v1.InstanceService.GetInstance:input_type -> orzbob.cloud.api.v1.GetInstanceRequest
	6,  // 11: orzbob.cloud.api.v1.InstanceService.ListInstances:input_type -> orzbob.cloud.api.v1.ListInstancesRequest
	8,  // 12: orzbob.cloud.api.v1.InstanceService.DeleteInstance:input_type -> orzbob.cloud.api.v1.DeleteInstanceRequest
	10, // 13: orzbob.cloud.api.v1.InstanceService.Attach:input_type -> orzbob.cloud.api.v1.AttachRequest
	3,  // 14: orzbob.cloud.api.v1.InstanceService.CreateInstance:output_type -> orzbob.cloud.api.v1.CreateInstanceResponse
	5,  // 15: orzbob.cloud.api.v1.InstanceService.GetInstance:output_type -> orzbob.cloud.api.v1.GetInstanceResponse
	7,  // 16: orzbob.cloud.api.v1.InstanceService.ListInstances:output_type -> orzbob.cloud.api.v1.ListInstancesResponse
	9,  // 17: orzbob.cloud.api.v1.InstanceService.DeleteInstance:output_type -> orzbob.cloud.api.v1.DeleteInstanceResponse
	11, // 18: orzbob.cloud.api.v1.InstanceService.Attach:output_type -> orzbob.cloud.api.v1.AttachResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_cloud_api_instance_proto_init() }
func file_internal_cloud_api_instance_proto_init() {
	if File_internal_cloud_api_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cloud_api_instance_proto_rawDesc), len(file_internal_cloud_api_instance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_cloud_api_instance_proto_goTypes,
		DependencyIndexes: file_internal_cloud_api_instance_proto_depIdxs,
		EnumInfos:         file_internal_cloud_api_instance_proto_enumTypes,
		MessageInfos:      file_internal_cloud_api_instance_proto_msgTypes,
	}.Build()
	File_internal_cloud_api_instance_proto = out.File
	file_internal_cloud_api_instance_proto_goTypes = nil
	file_internal_cloud_api_instance_proto_depIdxs = nil
}
